#pragma once



#include "GameObject.h"
#include "GameUnit.h"
#include "GameChampion.h"
#include "GameMissile.h"
#include "GameSpell.h"
#include "GameBuff.h"
#include "GameItemSlot.h"

#include "SpellInfo.h"
#include "ItemInfo.h"
#include "UnitInfo.h"

#include "ObjectQuery.h"

#include "Color.h"

#include "PyExecutionContext.h"
#include "GameState.h"

using namespace boost::python;

/// Interfacing module between C++ & python
BOOST_PYTHON_MODULE(valkyrie) {

	register_exception_translator<QueryException>([](QueryException const& exc) { 
		PyErr_SetString(PyExc_RuntimeError, Strings::Format("Object Query Exception: %s", exc.what()).c_str());
	});

		class_<ConfigSet>("Config", "Interface for saving & loading script configurations")
		.def("set_int",                  &ConfigSet::SetInt,    "[set_int(self, key: str, value: int)]"                "Saves an integer to the config file")
		.def("set_bool",                 &ConfigSet::SetBool,   "[set_bool(self, key: str, value: bool)]"              "Saves a bool to the config file")
		.def("set_float",                &ConfigSet::SetFloat,  "[set_float(self, key: str, value: float)]"            "Saves a float to the config file")
		.def("set_str",                  &ConfigSet::SetStr,    "[set_str(self, key: str, value: str)]"                "Saves a string to the config file")
		.def("get_int",                  &ConfigSet::GetInt,    "[get_int(self, key: str, default: int) -> int]"       "Gets an integer from the config file")
		.def("get_bool",                 &ConfigSet::GetBool,	"[get_bool(self, key: str, default: bool) -> bool]"    "Gets a bool from the config file")
		.def("get_float",                &ConfigSet::GetFloat,	"[get_float(self, key: str, default: float) -> float]" "Gets a float from the config file")
		.def("get_str",                  &ConfigSet::GetStr,	"[get_str(self, key: str, default: str) -> str]"       "Gets a string from the config file")
		;

	class_<ImVec4>("Col", init<float, float, float, float>())
		.def_readonly("Black",           &Color::BLACK,            "[Col]")
		.def_readonly("White",           &Color::WHITE,            "[Col]")
		.def_readonly("Red",             &Color::RED,              "[Col]")
		.def_readonly("DarkRed",         &Color::DARK_RED,         "[Col]")
		.def_readonly("Green",           &Color::GREEN,            "[Col]")
		.def_readonly("DarkGreen",       &Color::DARK_GREEN,       "[Col]")
		.def_readonly("Yellow",          &Color::YELLOW,           "[Col]")
		.def_readonly("DarkYellow",      &Color::DARK_YELLOW,      "[Col]")
		.def_readonly("Cyan",            &Color::CYAN,             "[Col]")
		.def_readonly("Purple",          &Color::PURPLE,           "[Col]")
		.def_readonly("Gray",            &Color::GRAY,             "[Col]")
		.def_readonly("Orange",          &Color::ORANGE,           "[Col]")
		.def_readonly("Blue",            &Color::BLUE,             "[Col]")
		.def_readonly("Brown",           &Color::BROWN,            "[Col]")

		.def_readwrite("r",              &ImVec4::x,               "[float] Red value of color")
		.def_readwrite("g",              &ImVec4::y,               "[float] Green value of color")
		.def_readwrite("b",              &ImVec4::z,               "[float] Blue value of color")
		.def_readwrite("a",              &ImVec4::w,               "[float] Alpha value of color")
		;

	class_<Vector4>("Vec4", init<float, float, float, float>())
		.def_readwrite("x",              &Vector4::x,         "[float]")
		.def_readwrite("y",              &Vector4::y,         "[float]")
		.def_readwrite("z",              &Vector4::z,         "[float]")
		.def_readwrite("w",              &Vector4::w,         "[float]")
		.def("length",                   &Vector4::length,    "[length(self) -> float]")
		.def("normalize",                &Vector4::normalize, "[normalize(self) -> float]")
		.def("distance",                 &Vector4::distance,  "[distance(self, other: Vec4) -> float]")
		.def("__mul__",                  &Vector4::scale)
		.def("__mul__",                  &Vector4::vscale)
		.def("__add__",                  &Vector4::add)
		.def("__sub__",                  &Vector4::sub)
		.def("clone",                    &Vector4::clone,   "[clone(self) -> Vec4]")
		;

	class_<Vector3>("Vec3", init<float, float, float>())
		.def_readwrite("x",              &Vector3::x,        "[float]")
		.def_readwrite("y",              &Vector3::y,        "[float]")
		.def_readwrite("z",              &Vector3::z,        "[float]")
		.def("length",                   &Vector3::length,   "[length(self) -> float]")
		.def("normalize",                &Vector3::normalize,"[normalize(self) -> float]")
		.def("distance",                 &Vector3::distance, "[distance(self, other: Vec3) -> float]")
		.def("__mul__",                  &Vector3::scale)
		.def("__mul__",                  &Vector3::vscale)
		.def("l1",                       &Vector3::l1,       "[l1(self, other: Vec3) -> float]"       "L1 Distance")
		.def("rotate_x",                 &Vector3::rotate_x, "[rotate_x(self, angle: float) -> Vec3]" "Rotates the vector along the x axis")
		.def("rotate_y",                 &Vector3::rotate_y, "[rotate_y(self, angle: float) -> Vec3]" "Rotates the vector along the y axis")
		.def("rotate_z",                 &Vector3::rotate_z, "[rotate_z(self, angle: float) -> Vec3]" "Rotates the vector along the z axis")
		.def("__add__",                  &Vector3::add)
		.def("__sub__",                  &Vector3::sub)
		.def("angle",                    &Vector3::angle,    "[angle(self, other: Vec3)]"             "Angle between two vectors")
		.def("dot",                      &Vector3::dot,      "[dot(self, other: Vec3) -> float]"      "Calculates dot product")
		.def("clone",                    &Vector3::clone,    "[clone(self) -> Vec3]"                  "Clones vector")
		;

	class_<Vector2>("Vec2", init<float, float>())
		.def_readwrite("x",              &Vector2::x,         "[float]")
		.def_readwrite("y",              &Vector2::y,         "[float]")
		.def("length",                   &Vector2::length,    "[length(self) -> float]")
		.def("normalize",                &Vector2::normalize, "[normalize(self) -> float]")
		.def("distance",                 &Vector2::distance,  "[distance(self, other: Vec2) -> float]")
		.def("__mul__",                  &Vector2::scale)
		.def("__mul__",                  &Vector2::vscale)
		.def("__add__",                  &Vector2::add)
		.def("__sub__",                  &Vector2::sub)
		.def("clone",                    &Vector2::clone,     "[clone(self) -> Vec2] Clones vector")
		;

	enum_<SummonerType>("Summoner", "Represents the type of a summoner spell")
		.value("Smite",                   SummonerSmite)
		.value("Ignite",                  SummonerIgnite)
		.value("Cleanse",                 SummonerCleanse)
		.value("Teleport",                SummonerTeleport)
		.value("Flash",                   SummonerFlash)
		.value("HexFlash",                SummonerHexFlash)
		.value("Snowball",                SummonerSnowball)
		.value("Clarity",                 SummonerClarity)
		.value("Exhaust",                 SummonerExhaust)
		.value("Barrier",                 SummonerBarrier)
		.value("Heal",                    SummonerHeal)
		.value("Ghost",                   SummonerGhost)
		.value("Unknown",                 SummonerUnknown)
		;

	enum_<ImGuiWindowFlags>("WindowFlag", "Represents imgui window flags. These support bitwise operations so WindowFlag.NoResize | WindowFlag.NoMove would yield a flag with both")
		.value("NoFlags",                   ImGuiWindowFlags_None)
		.value("NoTitleBar",                ImGuiWindowFlags_NoTitleBar)
		.value("NoResize",                  ImGuiWindowFlags_NoResize)
		.value("NoMove",                    ImGuiWindowFlags_NoMove)
		.value("NoScrollbar",               ImGuiWindowFlags_NoScrollbar)
		.value("NoScrollWithMouse",         ImGuiWindowFlags_NoScrollWithMouse)
		.value("NoCollapse",                ImGuiWindowFlags_NoCollapse)
		.value("AlwaysAutoResize",          ImGuiWindowFlags_AlwaysAutoResize)
		.value("NoBackground",              ImGuiWindowFlags_NoBackground)
		.value("NoSavedSettings",           ImGuiWindowFlags_NoSavedSettings)
		.value("NoMouseInputs",             ImGuiWindowFlags_NoMouseInputs)
		.value("MenuBar",                   ImGuiWindowFlags_MenuBar)
		.value("HorizontalScrollbar",       ImGuiWindowFlags_HorizontalScrollbar)
		.value("NoFocusOnAppearing",        ImGuiWindowFlags_NoFocusOnAppearing)
		.value("NoBringToFrontOnFocus",     ImGuiWindowFlags_NoBringToFrontOnFocus)
		.value("AlwaysVerticalScrollbar",   ImGuiWindowFlags_AlwaysVerticalScrollbar)
		.value("AlwaysHorizontalScrollbar", ImGuiWindowFlags_AlwaysHorizontalScrollbar)
		.value("AlwaysUseWindowPadding",    ImGuiWindowFlags_AlwaysUseWindowPadding)
		.value("NoNavInputs",               ImGuiWindowFlags_NoNavInputs)
		.value("NoNavFocus",                ImGuiWindowFlags_NoNavFocus)
		.value("UnsavedDocument",           ImGuiWindowFlags_UnsavedDocument)
		.value("NoNav",                     ImGuiWindowFlags_NoNav)
		.value("NoDecoration",              ImGuiWindowFlags_NoDecoration)
		.value("NoInputs",                  ImGuiWindowFlags_NoInputs)
		;

	enum_<RaycastLayer>("RayLayer", "Represents the objects that a raycast can intercept")
		.value("Champion",                  RayChampion)
		.value("Minion",                    RayMinion)
		.value("Turret",                    RayTurret)
		.value("Jungle",                    RayJungle)
		.value("Missile",                   RayMissile)
		.value("Other",                     RayOther)
		.value("Wall",                      RayWall)
		.value("Unit",                      RayUnit)
		.value("All",                       RayAll)
		.value("Enemy",                     RayEnemy)
		.value("Ally",                      RayAlly)
		;

	enum_<ImGuiStyleVar>("StyleVar")
		.value("Alpha",               ImGuiStyleVar_Alpha)
		.value("WindowPadding",       ImGuiStyleVar_WindowPadding)
		.value("WindowRounding",      ImGuiStyleVar_WindowRounding)
		.value("WindowBorderSize",    ImGuiStyleVar_WindowBorderSize)
		.value("WindowMinSize",       ImGuiStyleVar_WindowMinSize)
		.value("WindowTitleAlign",    ImGuiStyleVar_WindowTitleAlign)
		.value("ChildRounding",       ImGuiStyleVar_ChildRounding)
		.value("ChildBorderSize",     ImGuiStyleVar_ChildBorderSize)
		.value("PopupRounding",       ImGuiStyleVar_PopupRounding)
		.value("PopupBorderSize",     ImGuiStyleVar_PopupBorderSize)
		.value("FramePadding",        ImGuiStyleVar_FramePadding)
		.value("FrameRounding",       ImGuiStyleVar_FrameRounding)
		.value("FrameBorderSize",     ImGuiStyleVar_FrameBorderSize)
		.value("ItemSpacing",         ImGuiStyleVar_ItemSpacing)
		.value("ItemInnerSpacing",    ImGuiStyleVar_ItemInnerSpacing)
		.value("IndentSpacing",       ImGuiStyleVar_IndentSpacing)
		.value("CellPadding",         ImGuiStyleVar_CellPadding)
		.value("ScrollbarSize",       ImGuiStyleVar_ScrollbarSize)
		.value("ScrollbarRounding",   ImGuiStyleVar_ScrollbarRounding)
		.value("GrabMinSize",         ImGuiStyleVar_GrabMinSize)
		.value("GrabRounding",        ImGuiStyleVar_GrabRounding)
		.value("TabRounding",         ImGuiStyleVar_TabRounding)
		.value("ButtonTextAlign",     ImGuiStyleVar_ButtonTextAlign)
		.value("SelectableTextAlign", ImGuiStyleVar_SelectableTextAlign)
		;

	enum_<SpellFlags>("Spell", "Spell flags that specify behaviour and type of a spell")
		.value("CastPoint",       CastPoint)
		.value("CastAnywhere",    CastAnywhere)
		.value("CastTarget",      CastTarget)
		.value("CastDirection",   CastDirection)
								  
		.value("TypeLine",        TypeLine)
		.value("TypeArea",        TypeArea)
		.value("TypeCone",        TypeCone)

		.value("CollideWindwall", CollideWindwall)
		.value("CollideMinion",   CollideMinion)
		.value("CollideChampion", CollideChampion)
		.value("CollideMonster",  CollideMonster)

		.value("AffectMinion",    AffectMinion)
		.value("AffectChampion",  AffectChampion)
		.value("AffectMonster",   AffectMonster)

		.value("CollideCommon",   CollideCommon)
		.value("AffectAllUnits",  AffectAllUnits)

		.value("DashSkill",       DashSkill)
		.value("ChannelSkill",    ChannelSkill)
		.value("ChargeableSkill", ChargeableSkill)
		.value("AppliesOnHit",    AppliesOnHit)
		;

	enum_<HKey>("Key", "Hardware key codes")
		.value("no_key",       NO_KEY)             
		.value("esc",          ESC)
		.value("n1",           N_1)
		.value("n2",           N_2)
		.value("n3",           N_3)
		.value("n4",           N_4)
		.value("n5",           N_5)
		.value("n6",           N_6)
		.value("n7",           N_7)
		.value("n8",           N_8)
		.value("n9",           N_9)
		.value("n0",           N_0)
		.value("minus",        MINUS)
		.value("equal",        EQUAL)
		.value("bs",           BS)
		.value("tab",          Tab)
		.value("q",            Q)
		.value("w",            W)
		.value("e",            E)
		.value("r",            R)
		.value("t",            T)
		.value("y",            Y)
		.value("u",            U)
		.value("i",            I)
		.value("o",            O)
		.value("p",            P)
		.value("lbracket",     LBRACKET)
		.value("rbracket",     RBRACKET)
		.value("enter",        ENTER)
		.value("ctrl",         CTRL)
		.value("a",            A)
		.value("s",            S)
		.value("d",            D)
		.value("f",            F)
		.value("g",            G)
		.value("h",            H)
		.value("j",            J)
		.value("k",            K)
		.value("l",            L)
		.value("semicolon",    SEMICOLON)
		.value("single_quote", SINGLE_QUOTE)
		.value("tilde",        TILDE)
		.value("lshift",       LSHIFT)
		.value("backslash",    BACKSLASH)
		.value("z",            Z)
		.value("x",            X)
		.value("c",            C)
		.value("v",            V)
		.value("b",            B)
		.value("n",            N)
		.value("m",            M)
		.value("comma",        COMMA)
		.value("dot",          DOT)
		.value("frontslash",   FRONTSLASH)
		.value("rshift",       RSHIFT)
		.value("print_screen", PRINT_SCREEN)
		.value("alt",          ALT)
		.value("space",        SPACE)
		.value("caps",         CAPS)
		.value("f1",           F1)
		.value("f2",           F2)
		.value("f3",           F3)
		.value("f4",           F4)
		.value("f5",           F5)
		.value("f6",           F6)
		.value("f7",           F7)
		.value("f8",           F8)
		.value("f9",           F9)
		.value("f10",          F10)
		.value("num",          NUM)
		.value("scroll",       SCROLL)
		.value("home",         HOME)
		.value("up",           UP)
		.value("page_up",      PAGE_UP)
		.value("num_minus",    NUM_MINUS)
		.value("left",         LEFT)
		.value("center",       CENTER)
		.value("right",        RIGHT)
		.value("plus",         PLUS)
		.value("end",          END)
		.value("down",         DOWN)
		.value("page_down",    PAGE_DOWN)
		.value("insert",       INSERT)
		.value("delte",        DEL)                
		;
	
	enum_<MapType>("MapType", "Map type SRU = Summoners Rift, HA = Howling Abyss")
		.value("SRU",          GAME_MAP_SRU)
		.value("HA",           GAME_MAP_HA)
		;

	enum_<UnitTag>("Unit", "Riot unit tags extracted from the game files. These are not compatible with bitwise operations so writing things like Unit.Monster | Unit.Plant will not yield a tag that has both of those.")
		.value("Champion",                    UnitTag::Unit_Champion)
		.value("ChampionClone",               UnitTag::Unit_Champion_Clone)
		.value("IsolationNonImpacting",       UnitTag::Unit_IsolationNonImpacting)
		.value("KingPoro",                    UnitTag::Unit_KingPoro)
		.value("Minion",                      UnitTag::Unit_Minion)
		.value("MinionLane",                  UnitTag::Unit_Minion_Lane)
		.value("MinionLaneMelee",             UnitTag::Unit_Minion_Lane_Melee)
		.value("MinionLaneRanged",            UnitTag::Unit_Minion_Lane_Ranged)
		.value("MinionLaneSiege",             UnitTag::Unit_Minion_Lane_Siege)
		.value("MinionLaneSuper",             UnitTag::Unit_Minion_Lane_Super)
		.value("MinionSummon",                UnitTag::Unit_Minion_Summon)
		.value("MinionSummon_Large",          UnitTag::Unit_Minion_Summon_Large)
		.value("Monster",                     UnitTag::Unit_Monster)
		.value("MonsterBlue",                 UnitTag::Unit_Monster_Blue)
		.value("MonsterBuff",                 UnitTag::Unit_Monster_Buff)
		.value("MonsterCamp",                 UnitTag::Unit_Monster_Camp)
		.value("MonsterCrab",                 UnitTag::Unit_Monster_Crab)
		.value("MonsterDragon",               UnitTag::Unit_Monster_Dragon)
		.value("MonsterEpic",                 UnitTag::Unit_Monster_Epic)
		.value("MonsterGromp",                UnitTag::Unit_Monster_Gromp)
		.value("MonsterKrug",                 UnitTag::Unit_Monster_Krug)
		.value("MonsterLarge",                UnitTag::Unit_Monster_Large)
		.value("MonsterMedium",               UnitTag::Unit_Monster_Medium)
		.value("MonsterRaptor",               UnitTag::Unit_Monster_Raptor)
		.value("MonsterRed",                  UnitTag::Unit_Monster_Red)
		.value("MonsterWolf",                 UnitTag::Unit_Monster_Wolf)
		.value("Plant",                       UnitTag::Unit_Plant)
		.value("Special",                     UnitTag::Unit_Special)
		.value("SpecialAzirR",                UnitTag::Unit_Special_AzirR)
		.value("SpecialAzirW",                UnitTag::Unit_Special_AzirW)
		.value("SpecialCorkiBomb",            UnitTag::Unit_Special_CorkiBomb)
		.value("SpecialEpicMonsterIgnores",   UnitTag::Unit_Special_EpicMonsterIgnores)
		.value("SpecialKPMinion",             UnitTag::Unit_Special_KPMinion)
		.value("SpecialMonsterIgnores",       UnitTag::Unit_Special_MonsterIgnores)
		.value("SpecialPeaceful",             UnitTag::Unit_Special_Peaceful)
		.value("SpecialSyndraSphere",         UnitTag::Unit_Special_SyndraSphere)
		.value("SpecialTeleportTarget",       UnitTag::Unit_Special_TeleportTarget)
		.value("SpecialTrap",                 UnitTag::Unit_Special_Trap)
		.value("SpecialTunnel",               UnitTag::Unit_Special_Tunnel)
		.value("SpecialTurretIgnores",        UnitTag::Unit_Special_TurretIgnores)
		.value("SpecialUntargetableBySpells", UnitTag::Unit_Special_UntargetableBySpells)
		.value("SpecialVoid",                 UnitTag::Unit_Special_Void)
		.value("SpecialYorickW",              UnitTag::Unit_Special_YorickW)
		.value("Structure",                   UnitTag::Unit_Structure)
		.value("StructureInhibitor",          UnitTag::Unit_Structure_Inhibitor)
		.value("StructureNexus",              UnitTag::Unit_Structure_Nexus)
		.value("StructureTurret",             UnitTag::Unit_Structure_Turret)
		.value("StructureTurretInhib",        UnitTag::Unit_Structure_Turret_Inhib)
		.value("StructureTurretInner",        UnitTag::Unit_Structure_Turret_Inner)
		.value("StructureTurretNexus",        UnitTag::Unit_Structure_Turret_Nexus)
		.value("StructureTurretOuter",        UnitTag::Unit_Structure_Turret_Outer)
		.value("StructureTurretShrine",       UnitTag::Unit_Structure_Turret_Shrine)
		.value("Ward",                        UnitTag::Unit_Ward)
		;

	class_<GameMap>("Map", "Object representing the current game map")
		.def_readonly("type",                &GameMap::type,            "[MapType] A enum value representing the currently played map")
		;
	
	class_<GameKeybind>("Keybind", "Contains game keybinds")
		.def_readonly("cast_q",              &GameKeybind::CastSpellQ,          "[Key] Key for casting Q spell")
		.def_readonly("cast_w",              &GameKeybind::CastSpellW,          "[Key] Key for casting W spell")
		.def_readonly("cast_e",              &GameKeybind::CastSpellE,          "[Key] Key for casting E spell")
		.def_readonly("cast_r",              &GameKeybind::CastSpellR,          "[Key] Key for casting R spell")
		.def_readonly("cast_d",              &GameKeybind::CastSpellD,          "[Key] Key for casting D spell")
		.def_readonly("cast_f",              &GameKeybind::CastSpellF,          "[Key] Key for casting F spell")
										     							        
		.def_readonly("use_item_1",          &GameKeybind::UseItem1,            "[Key] Key for using item on slot 1")
		.def_readonly("use_item_2",          &GameKeybind::UseItem2,            "[Key] Key for using item on slot 2")
		.def_readonly("use_item_3",          &GameKeybind::UseItem3,            "[Key] Key for using item on slot 3")
		.def_readonly("use_item_4",          &GameKeybind::UseItem4,            "[Key] Key for using item on slot 4")
		.def_readonly("use_item_5",          &GameKeybind::UseItem5,            "[Key] Key for using item on slot 5")
		.def_readonly("use_item_6",          &GameKeybind::UseItem6,            "[Key] Key for using item on slot 6")
		.def_readonly("use_trinket",         &GameKeybind::UseItemTrinket,      "[Key] Key for using trinket")
										     
		.def_readonly("recall",              &GameKeybind::Recall,              "[Key] Key for recalling")
		.def_readonly("target_champ_only",   &GameKeybind::TargetChampionsOnly, "[Key] Key for target champion only")
		;

	class_<GameHud>("GameHud", "Contains info about the hud in the game")
		.def_readonly("minimap_pos",         &GameHud::minimapPosition,   "[Vec2] Position of the minimap on the screen")
		.def_readonly("minimap_size",        &GameHud::minimapSize,       "[Vec2] Size of the minimap on the screen")
		.def_readonly("cursor_world_pos",    &GameHud::mouseWorldPos,     "[Vec3] Position of mouse cursor in world coordinates")
		.def_readonly("chat_open",           &GameHud::isChatOpen,        "[bool] True if chat is open")
		;

	class_<RaycastResult>("RaycastResult", "Represents the result of a raycast")
		.def_readonly("point",               &RaycastResult::point,       "[Vec3] Point of raycast collision")
		.def_readonly("obj",                 &RaycastResult::GetObjectPy, "[Obj] Object that the raycast collided with. None if it was a wall")
		;

	class_<FutureCollision>("FutureCollision", "Information about a future collision between a spell and a unit")
		.def_readonly("spell",               &FutureCollision::GetCastPy,          "[SpellCast] The spell in the collision")
		.def_readonly("unit",                &FutureCollision::GetUnitPy,          "[UnitObj] The unit in the collision")
		.def_readonly("unit_pos",            &FutureCollision::unitCollisionPoint, "[Vec3] The unit position at the moment of collision")
		.def_readonly("spell_pos",           &FutureCollision::castCollisionPoint, "[Vec3] The spell position at the moment of collision")
		.def_readonly("final",               &FutureCollision::isFinal,            "[bool] True if the projectile will not go further after this collision. Useful for drawing indicators")
		.def_readonly("time_until_impact",   &FutureCollision::timeUntilImpact,    "[float] Time in seconds until the collision occurs")
		;

	class_<GameBuff>("Buff", "Contains data related to a buff on a champion")
		.def_readonly("name",                &GameBuff::name,        "[str] Name of the buff")
		.def_readonly("time_begin",          &GameBuff::startTime,   "[float] When the buff was received in game time")
		.def_readonly("time_end",            &GameBuff::endTime,     "[float] When the buff will end in game time")
		.def_readonly("count",               &GameBuff::count,       "[int] Number of stacks of the buff")
		.def_readonly("value",               &GameBuff::value,       "[int] Value of the buff")
		;

	class_<UnitInfo>("UnitStatic",         "Static data loaded at runtime for an unit")
		.def_readonly("hp_bar_height",       &UnitInfo::healthBarHeight,     "[float] The height at which the health bar starts")
		.def_readonly("movement_speed",      &UnitInfo::baseMovementSpeed,   "[float] Base movement speed")
		.def_readonly("base_atk_range",      &UnitInfo::baseAttackRange,     "[float] Base attack range")
		.def_readonly("base_atk_speed",      &UnitInfo::baseAttackSpeed,     "[float] Base attack speed")
		.def_readonly("atk_speed_ratio",     &UnitInfo::attackSpeedRatio,    "[float] Attack speed ratio")
											 								   
		.def_readonly("acquisition_radius",  &UnitInfo::acquisitionRange,    "[float] Acquisition radius. See league wiki for more info")
		.def_readonly("selection_radius",    &UnitInfo::selectionRadius,     "[float] Selection radius. See league wiki for more info")
		.def_readonly("pathing_radius",      &UnitInfo::pathRadius,          "[float] Pathing radius. See league wiki for more info")
		.def_readonly("gameplay_radius",     &UnitInfo::gameplayRadius,      "[float] Gameplay radius. See league wiki for more info")
											 								   
		.def_readonly("basic_atk",           &UnitInfo::GetBasicAttack,      "[SpellStatic] Default basic attack on the unit")
		.def_readonly("basic_atk_windup",    &UnitInfo::basicAttackWindup,   "[float] Basic attack windup. See league wiki for more info")
		.def_readonly("basic_atk_cast_time", &UnitInfo::basicAttackCastTime, "[float] Basic attack cast time. See league wiki for more info")
		;

	class_<GameItemSlot>("ItemSlot", "Represents an item slot")
		.def_readonly("charges",             &GameItemSlot::charges,          "[int] Charges of item (example: corruption potion charges, number of red potions etc)")
		.def_readonly("item",                &GameItemSlot::GetItemPy,        "[ItemStatic] Static data of the item. If there is no item on the slot then this is None otherwise it is an ItemStatic instance")
		.def_readonly("active",              &GameItemSlot::GetActivePy,      "[SpellObj] Spell active of the item. None if item doesnt have active")
		;

	class_<ItemInfo>("ItemStatic",        "Static data loaded at runtime for an item")
		.def_readonly("id",                &ItemInfo::id,                    "[int] Item internal id")
		.def_readonly("cost",              &ItemInfo::cost,                  "[float] Cost of item in gold coins")
		.def_readonly("mov_speed",         &ItemInfo::movementSpeed,         "[float] Flat movement speed given by item")
		.def_readonly("health",            &ItemInfo::health,                "[float] Flat health given by item")
		.def_readonly("crit",              &ItemInfo::crit,                  "[float] Crit chance given by item")
		.def_readonly("ap",                &ItemInfo::abilityPower,          "[float] Flat ability power given by item")
		.def_readonly("mana",              &ItemInfo::mana,                  "[float] Flat mana given by item")
		.def_readonly("armor",             &ItemInfo::armour,                "[float] Flat armour given by item")
		.def_readonly("magic_res",         &ItemInfo::magicResist,           "[float] Flat magic resist given by item")
		.def_readonly("phys_dmg",          &ItemInfo::physicalDamage,        "[float] Flat physical damage given by item")
		.def_readonly("atk_speed",         &ItemInfo::attackSpeed,           "[float] Attack speed percent given by item")
		.def_readonly("life_steal",        &ItemInfo::lifeSteal,             "[float] Life steal percent given by item")
		.def_readonly("hp_regen",          &ItemInfo::hpRegen,               "[float] Health regen percent given by item")
		.def_readonly("mov_speed_percent", &ItemInfo::movementSpeedPercent,  "[float] Movement speed percent given by item")
		;

	class_<SpellInfo>("SpellStatic",      "Static data loaded at runtime for a spell")
		.def_readonly("name",              &SpellInfo::name,                 "[str] Name of the spell in lower case")
		.def_readonly("icon",              &SpellInfo::icon,                 "[str] Icon name of the spell in lowercase")
		.def_readonly("cast_time",         &SpellInfo::castTime,             "[float] Cast time of spell")
		.def_readonly("cast_range",        &SpellInfo::castRange,            "[float] Cast range of the spell. Can mean multiple things, the range of a skillshot or the cast range of targeted spell")
		.def_readonly("cast_radius",       &SpellInfo::castRadius,           "[float] Cast radius of the spell (e.g Ziggs R area of effect)")
		.def_readonly("cast_cone_angle",   &SpellInfo::castConeAngle,        "[float] If spell is conic this is the cone angle")
		.def_readonly("cast_cone_distance",&SpellInfo::castConeDistance,     "[float] If the spell is conic this is the cone length")
		.def_readonly("delay",             &SpellInfo::delay,                "[float] Additional delay besides the cast_time. Also if a missile has fixed travel time the value will be added here.")
		.def_readonly("width",             &SpellInfo::width,                "[float] Width of the spell")
		.def_readonly("height_augment",    &SpellInfo::height,               "[float] For drawing purposes. Height of the missile/spell must be augmented by this value")
		.def_readonly("speed",             &SpellInfo::speed,                "[float] Speed of the spell. Used mostly by missile spells")
		.def("has_flag",                   &SpellInfo::HasFlag,              "[has_flag(self, flag: Spell) -> bool] Checks if the spell has the specified Spell flag")
		;

	class_<GameObject>("Obj",             "Represents the base of a ingame object. Most ingame objects derive from this.")
		.def_readonly("name",              &GameObject::name,                "[str] Name of the object in lower case")
		.def_readonly("index",             &GameObject::index,               "[int] Index of the object. This is not a unique id, you use this for targeted spells to find who the target is")
		.def_readonly("net_id",            &GameObject::networkId,           "[int] Network id. This is a unique id of the object")
		.def_readonly("team",              &GameObject::team,                "[int] Team of the object: possible values 100, 200 and 300 for jungle side. Use ally_to/enemy_to functions instead of this")
		.def_readonly("pos",               &GameObject::pos,                 "[Vec3] Position of the object")
		.def_readonly("visible",           &GameObject::isVisible,           "[bool] True if object is visible")
		.def_readonly("last_seen",         &GameObject::lastSeen,            "[float] Timestamp in game time for when the object was last visible")
		.def_readonly("first_seen",        &GameObject::firstSeen,           "[float] When the object was first seen")
		.def_readonly("dir",               &GameObject::dir,                 "[Vec3] Direction the object is facing as a normalized Vec3")
		.def_readonly("bounding_radius",   &GameObject::GetRadius,           "[float] The bounding radius of the object a.k.a the hitbox (but its actually a circle)")
		
		.def("in_front_of",                &GameObject::InFrontOf,           "[in_front_of(self, other: Obj) -> bool]"   "Checks if object is in front of another object")
		.def("ally_to",                    &GameObject::IsAllyTo,            "[ally_to(self, other: Obj) -> bool]"       "Checks if two objects are allied")
		.def("enemy_to",                   &GameObject::IsEnemyTo,           "[enemy_to(self, other: Obj) -> bool]"      "Checks if two objects are enemies")
		.def("__eq__",                     &GameObject::EqualsTo,            "[__eq__(self, other: Obj) -> bool]"        "Checks if two object are identical by checking their network id")
		.def("menu_draw",                  &GameObject::ImGuiDraw,           "[menu_draw(self) -> bool]"                 "Draws the object in the current menu")
		;

	class_<GameSpell>("SpellObj",            "Represents a spell in game. In case of spells from items make sure level > 0 before casting it.")
		.def_readonly("name",              &GameSpell::name,                 "[str] Name of the spell in lower case")
		.def_readonly("lvl",               &GameSpell::lvl,                  "[int] Level of the spell. Has value 0 when spell is not learned")
		.def_readonly("ready_at",          &GameSpell::readyAt,              "[float] Timestamp in game time for when the cooldown of the spell ends")
		.def_readonly("value",             &GameSpell::value,                "[float] Value of spells. Holds the value of the spell for summoner spells like ignite/smite it holds the damage. For champion spells this value is usually 0")
		.def_readonly("cd",                &GameSpell::GetRemainingCooldown, "[float] The remaining cooldown of the spell. Internally it is calculated using ready_at")
		.def_readonly("mana",              &GameSpell::mana,                 "[float] Mana necessarry for casting the spell")
		.def_readonly("static",            &GameSpell::GetStaticData,        "[SpellStatic] Gets static information loaded at runtime about the spell. Can be None but normally shouldn't. If you find a object for which this is null please contact a dev")
		.def_readonly("key",               &GameSpell::castKey,              "[Key] Key bound to this spell")
		;

	class_<SummonerSpell, bases<GameSpell>>("SummonerSpell", "Represents a summoner spell")
		.def_readonly("type",              "[Summoner] Summoner spell type")
		;

	class_<SpellCast>("SpellCast",         "Has data about a spell being cast.")
		.def_readonly("start_pos",         &SpellCast::start,                "[Vec3] Start position of the spell. Usually the position of the caster")
		.def_readonly("end_pos",           &SpellCast::end,                  "[Vec3] End position of the spell. Use this to get the direction of the spell. Remarks: this might not always be the real endpoint check SpellStatic project_endpoint field for more information.")
		.def_readonly("dir",               &SpellCast::dir,                  "[Vec3] Direction the spell is facing (in case of missiles)")
		.def_readonly("src_index",         &SpellCast::srcIndex,             "[int] Index of the object who is casting")
		.def_readonly("dest_index",        &SpellCast::destIndex,            "[int] If casting a targeted spell this holds the index of the target object")
		.def_readonly("time_begin",        &SpellCast::timeBegin,            "[float] Start timestamp in game time of the casting")
		.def_readonly("cast_time",         &SpellCast::castTime,             "[float] Total cast time")
		.def_readonly("remaining",         &SpellCast::RemainingCastTime,    "[float] Remaining cast time. This can go into negatives since casts arent removed from memory always")
		.def_readonly("static",            &SpellCast::GetStaticData,        "[SpellStatic] Static data of the spell being cast. Can be None but normally shouldn't. If you find a object for which this is null please contact a dev")
		.def_readonly("name",              &SpellCast::name,                 "[str] Name of the spell being cast")
		;

	class_<GameMissile, bases<GameObject>>("MissileObj")
		.def_readonly("spell",             &GameMissile::GetSpell,           "[SpellCast] The spell of the missile. A spell can have multiple missiles. So this is not necessarily the spell that was cast.")
		;

	class_<GameUnit, bases<GameObject>>("UnitObj", "Represents a base unit object")
		.def_readonly("dead",              &GameUnit::isDead,                "[bool] Used to check if unit is dead")
		.def_readonly("targetable",        &GameUnit::targetable,            "[bool] Used to check if unit is targetable")
		.def_readonly("invulnerable",      &GameUnit::invulnerable,          "[bool] Used to check if unit is invulnerable")
		.def_readonly("mana",              &GameUnit::mana,                  "[float] Current mana of the unit")
		.def_readonly("max_mana",          &GameUnit::maxMana,               "[float] Max mana of the unit")
		.def_readonly("health",            &GameUnit::health,                "[float] Current health of the unit")
		.def_readonly("max_health",        &GameUnit::maxHealth,             "[float] Max health of the unit")
		.def_readonly("armor",             &GameUnit::armor,                 "[float] Total armor of the unit")
		.def_readonly("magic_res",         &GameUnit::magicRes,              "[float] Total magic resist of the unit")
		.def_readonly("atk",               &GameUnit::GetAttackDamage,       "[float] Total attack damage of the unit")
		.def_readonly("lethality",         &GameUnit::lethality,             "[float] Lethality of unit")
		.def_readonly("haste",             &GameUnit::haste,                 "[float] Haste of unit")
		.def_readonly("cdr",               &GameUnit::GetCooldownReduction,  "[float] Cooldown reduction of unit")
		.def_readonly("base_atk",          &GameUnit::baseAtk,               "[float] Base physical damage of the unit")
		.def_readonly("move_speed",        &GameUnit::moveSpeed,             "[float] Movement speed of the unit")
		.def_readonly("lvl",               &GameUnit::lvl,                   "[int] Level of the unit")
		.def_readonly("expiry",            &GameUnit::expiry,                "[float] Expiration duration in seconds. Used for units like wards")
		.def_readonly("crit",              &GameUnit::crit,                  "[float] Crit chance of the unit as a decimal")
		.def_readonly("crit_multi",        &GameUnit::critMulti,             "[float] Crit multi of the unit as a decimal")
		.def_readonly("ap",                &GameUnit::abilityPower,          "[float] Flat ability power of the unit")
		.def_readonly("atk_speed_multi",   &GameUnit::atkSpeedMulti,         "[float] Attack speed multiplier of the unit as a decimal. Multiply this with base attack speed to get current attack speed")
		.def_readonly("atk_range",         &GameUnit::attackRange,           "[float] Attack range of the unit")
		.def_readonly("atk_speed",         &GameUnit::GetAttackSpeed,        "[float] Calculates the attack speed of the unit")

		.def_readonly("bonus_move_speed",  &GameUnit::GetBonusMoveSpeed,     "[float] Bonus move speed of unit")
		.def_readonly("bonus_armor",       &GameUnit::bonusArmor,            "[float] Bonus armor of the unit")
		.def_readonly("bonus_magic_res",   &GameUnit::bonusMagicRes,         "[float] Bonus magic resist of the unit")
		.def_readonly("bonus_atk",         &GameUnit::bonusAtk,              "[float] Bonus physical damage of the unit (from items, buffs etc)")
		.def_readonly("bonus_atk_speed",   &GameUnit::GetBonusAttackSpeed,   "[float] Bonus attack speed of the unit")

		.def_readonly("curr_casting",      &GameUnit::GetCastingSpell,       "[SpellCast] Currently casting spell by the unit")
		.def_readonly("static",            &GameUnit::GetStaticData,         "[UnitStatic] Static data loaded at runtime of the unit. Can be None but normally shouldn't. If you find a object for which this is null please contact a dev")
		.def_readonly("is_ranged",         &GameUnit::IsRanged,              "[bool] True if unit is ranged")
		.def_readonly("buffs",             &GameUnit::BuffsToPy,             "[list[Buff]] List of all the buffs on the champion. Currently buffs are only read for the player champion and enemies due to performance reasons.")
		.def_readonly("moving",            &GameUnit::isMoving,              "[bool] True if unit is moving")
		.def_readonly("dashing",           &GameUnit::isDashing,             "[bool] True if unit is dashing")
		.def_readonly("dash_speed",        &GameUnit::dashSpeed,             "[float] Similar to move speed but when dashing")
		.def_readonly("path",              &GameUnit::GetPathPy,             "[list[Vec3]] Navigation path of the unit")
		.def_readonly("destination",       &GameUnit::destination,           "[Vec3] Navigation destination of the unit")

		.def("get_buff",                   &GameUnit::GetBuffPy,               "[get_buff(self, name : str) -> Buff]"                                  "Gets the buff with the name provided or None if nothing found")
		.def("num_buff_stacks",            &GameUnit::BuffStackCount,          "[num_buff_stacks(self, name : str) -> int]"                            "Gets the number of stacks for the buff given by the name")
		.def("effective_phys_dmg",         &GameUnit::EffectivePhysicalDamage, "[effective_phys_dmg(self, target: UnitObj, raw_dmg: float) -> float]"  "Calculates effective physical damage against target considering armor and armor penetration")
		.def("effective_magic_dmg",        &GameUnit::EffectiveMagicalDamage,  "[effective_magic_dmg(self, target: UnitObj, raw_dmg: float) -> float]" "Calculates effective magic damage against target considering magic res and magic res penetration")
		.def("has_tags",                   &GameUnit::HasTags,                 "[has_tags(self, tag_flag: Unit) -> bool]"                              "Checks if the unit has unit tags (see Unit class)")
		.def("path_distance",              &GameUnit::CalculatePathLength,     "[path_distance(self) -> float]"                                        "Calculates navigation path distance in game units")
		.def("predict_position",           &GameUnit::PredictPosition,         "[predict_position(self, time_future: float) -> float]"                 "Predicts position of unit in X seconds")
		.def("reskin",                     &GameUnit::Reskin,                  "[reskin(self, id: int)]"                                               "Changes the skin of the unit")
		.def("has_buff",                   &GameUnit::HasBuff,                 "[has_buff(self, buff: str) -> bool]"                                   "Check if champion has buff. The buff name is case sensitive")
		;

	class_<GameChampion, bases<GameUnit>>("ChampionObj", "Represents a champion object")
		.def("get_summoner",               &GameChampion::GetSummoner,       "[get_summoner(type: Summoner) -> SummonerSpell]"        "Gets the summoner spell with the specified type. Returns None if player doesnt have that summoner spell")
		.def("can_cast_spell",             &GameChampion::CanCast,           "[can_cast_spell(self, spell: SpellObj) -> bool]"        "Checks if champion can cast the GameSpell provided")
		.def("has_item",                   &GameChampion::HasItem,           "[has_item(self, item_id: int) -> bool]"                 "Check if champion has item with item id")
		.def("get_item",                   &GameChampion::GetItem,           "[get_item(self, item_id: int) -> ItemSlot]"             "Gets item slot that contains the item with the given id. If no item is found None is returned")

		.def_readonly("spells",            &GameChampion::SpellsToPy,        "[list[SpellObj]] List of all the champion spells. Remarks: First 4 spells are Q,W,E,R. Next two are D,F.The next 6 are item spells. Use Context.cast_spell to cast them. Only enemies and local player have item actives read for performance reasons")
		.def_readonly("item_slots",        &GameChampion::ItemsToPy,         "[list[ItemSlot]] List of inventory slots. If an item is on the slot then the value is an Item object otherwise None. Only local player and enemies have items read for performance reasons")
		.def_readonly("Q",                 &GameChampion::GetQ,              "[SpellObj] Get Q spell")
		.def_readonly("W",                 &GameChampion::GetW,              "[SpellObj] Get W spell")
		.def_readonly("E",                 &GameChampion::GetE,              "[SpellObj] Get E spell")
		.def_readonly("R",                 &GameChampion::GetR,              "[SpellObj] Get R spell")
		.def_readonly("hpbar_pos",         &GameChampion::GetHpBarPosition,  "[float] Height position of the HP bar of the champion")
		.def_readonly("recalling",         &GameChampion::recalling,         "[bool] True if champion is recalling")
		.def_readonly("recall_start_time", &GameChampion::recallStartTime,   "[float] Start time of the recall in game time. Use this only if recalling flag is True")
		.def_readonly("is_clone",          &GameChampion::IsClone,           "[bool] Checks if the champion is a clone")
		.def_readonly("channeling",        &GameChampion::channeling,        "[bool] True if player is channeling a spell")
		;

	class_<GameTurret, bases<GameUnit>>("TurretObj", "Represents a turret object")
		;

	class_<GameMinion, bases<GameUnit>>("MinionObj", "Represents a minion object")
		.def_readonly("hpbar_pos",         &GameMinion::GetHpBarPosition,    "[float] Height position of the HP bar of the minion")
		;
	
	class_<GameJungle, bases<GameUnit>>("JungleMobObj", "Represents a jungle mob object")
		;

	class_<PyImGui>("UI", "Used to draw imgui backed UIs. Each method is more or less the equivalent of the original imgui method. Check imgui documentation for more info")
		.def("begin",                    &PyImGui::Begin,                                    "[begin(self, name: str)]")
		.def("begin",                    &PyImGui::BeginWithFlags,                           "[begin(self, name: str, flags: WindowFlag)]")
		.def("beginchild",               &PyImGui::BeginChild,                               "[beginchild(self, name: str, flags: WindowFlag)]")
		.def("endchild",                 &PyImGui::EndChild,                                 "[endchild(self)]")
		.def("end",                      &PyImGui::End,                                      "[end(self)]")
		.def("pushvar",                  &PyImGui::PushStyleV,                               "[pushvar(self, style: StyleVar, value: Vec2)]")
		.def("popvar",                   &PyImGui::PopStyleV,                                "[popvar(self, style: StyleVar)]")
				
		.def("help",                     &PyImGui::Help,                                     "[help(self, msg: str)] Shows a help market in front of the next widget")
		.def("button",                   &PyImGui::Button,                                   "[button(self, txt: str) -> bool] ")
		.def("button",                   &PyImGui::ColorButton,                              "[button(self, txt: str, color: Col) -> bool] ")
		.def("colorpick",                &PyImGui::ColorPicker,                              "[colorpick(self, txt: str, color: Col) -> Col] ")
		.def("checkbox",                 &PyImGui::Checkbox,                                 "[checkbox(self, txt: str, checked: bool) -> bool] ")
		.def("text",                     &PyImGui::Text,                                     "[text(self, txt: str)] ")
		.def("text",                     &PyImGui::TextColored,                              "[text(self, txt: str, color: Col)] ")
		.def("text_color",               &PyImGui::TextColored,                              "[text_color(self, txt: str, color: Col)] ")
		.def("labeltext",                &PyImGui::LabelText,                                "[labeltext(self, label: str, txt: str)] ")
		.def("labeltext",                &PyImGui::LabelTextColored,                         "[labeltext(self, label: str, txt: str, color: Col)] ")
		.def("separator",                &PyImGui::Separator,                                "[separator(self)] ")
		.def("dragint",                  &PyImGui::DragInt,        PyImGui::DragIntOverloads("[dragint(self, txt: str, value: int, step: int, min_val: int, max_val: int) -> int] "))
		.def("dragfloat",                &PyImGui::DragFloat,    PyImGui::DragFloatOverloads("[dragfloat(self, txt: str, value: float, step: float, min_val: float, max_val: float) -> float] "))
		.def("keyselect",                &PyImGui::KeySelect,                                "[keyselect(self, txt: str, key, Key) -> Key] ")
		.def("sliderfloat",              &PyImGui::SliderFloat,                              "[sliderfloat(self, txt: str, value: float, min_val: float, max_val: float) -> float] ")
		.def("sliderint",                &PyImGui::SliderInt,                                "[sliderint(self, txt: str, value: int, min_val: int, max_val: int) -> int] ")
		.def("sliderenum",               &PyImGui::SliderEnum,                               "[sliderenum(self, txt: str, selected_name: str, selected: int, max_select: int) -> int] ")
		.def("progressbar",              &PyImGui::ProgressBar,                              "[progressbar(self, fraction: float, size: Vec2, text: str)] ")
		.def("image",                    &PyImGui::Image,            PyImGui::ImageOverloads("[image(self, id: str, size: Vec2, color: Col)] Draws an image in the menu"))

		.def("header",                   &PyImGui::CollapsingHeader,                         "[header(self, text: str) -> bool]")
		.def("treenode",                 &PyImGui::TreeNode,                                 "[treenode(self, text: str) -> bool]")
		.def("treepop",                  &PyImGui::TreePop,                                  "[treepop(self)]")
		.def("beginmenu",                &PyImGui::BeginMenu,                                "[beginmenu(self, text: str) -> bool]")
		.def("endmenu",                  &PyImGui::EndMenu,                                  "[endmenu(self)]")
		.def("opennext",                 &PyImGui::SetNextItemOpen,                          "[opennext(self)]")
		.def("openpopup",                &PyImGui::OpenPopup,                                "[openpopup(self, popup: str)]")
		.def("beginpopup",               &PyImGui::BeginPopup,                               "[beginpopup(self, text: str) -> bool]")
		.def("endpopup",                 &PyImGui::EndPopup,                                 "[endpopup(self)]")
		.def("beginmodal",               &PyImGui::BeginPopupModal,                          "[beginmodal(self, text: str) -> bool]")
		.def("closepopup",               &PyImGui::CloseCurrentPopup,                        "[closepopup(self)]")
		.def("selectable",               &PyImGui::Selectable,                               "[selectable(self, text: str) -> bool]")
																	                         
		.def("begintbl",                 &PyImGui::BeginTable,                               "[begintbl(self, text: str, num_columns: int) -> bool]")
		.def("endtbl",                   &PyImGui::EndTable,                                 "[endtbl(self)]")
		.def("tblnextrow",               &PyImGui::TableNextRow,                             "[tblnextrow(self)]")
		.def("tblcolumn",                &PyImGui::TableSetColumn,                           "[tblcolumn(self, column: int)]")
		.def("inputtext",                &PyImGui::InputText,                                "[inputtext(self, label: str, input: str) -> str]")
						                 							                         
		.def("sameline",                 &PyImGui::SameLine,                                 "[sameline(self)]")
		.def("begingroup",               &PyImGui::BeginGroup,                               "[begingroup(self)]")
		.def("endgroup",                 &PyImGui::EndGroup,                                 "[endgroup(self)]")
						                 							                         
		.def("listbox",                  &PyImGui::ListBox,                                  "[listbox(self, items: list[str], current: int) -> int] ")
		.def("combo",                    &PyImGui::Combo,                                    "[combo(self, items: list[str], current: int) -> int] ")
		.def("demo",                     &PyImGui::Demo,                                     "[demo(self)] Shows the famous imgui demo")
																	                         
		.def("pushid",                   &PyImGui::PushId,                                   "[pushid(self, id: int)] ")
		.def("popid",                    &PyImGui::PopId,                                    "[popid(self)] ")
		.def("indent",                   &PyImGui::Indent,                                   "[indent(self, space: float)] ")
		;

	class_<ObjectQuery>("ObjectQuery", "Used to query game objects by avoiding python to C++ call overhead.")
		.def("get",                      &ObjectQuery::GetResultsPy,   "[get(self) -> list[Obj]] Returns the objects from the query")
		.def("count",                    &ObjectQuery::Count,          "[count(self) -> int] Makes the query but returns just the number of objects")

		.def("has_tag",                  &ObjectQuery::HasTag,         return_value_policy<reference_existing_object>(),     "[has_tag(self, tag: Unit) -> ObjectQuery]"   "Query units with specified tag")
		.def("ally_to",                  &ObjectQuery::AllyTo,         return_value_policy<reference_existing_object>(),     "[ally_to(self, other: Obj) -> ObjectQuery]"  "Query allies")
		.def("enemy_to",                 &ObjectQuery::EnemyTo,        return_value_policy<reference_existing_object>(),     "[enemy_to(self, other: Obj) -> ObjectQuery]" "Query enemies")
		.def("near",                     &ObjectQuery::NearObj,        return_value_policy<reference_existing_object>(),     "[near(self, obj: Obj) -> ObjectQuery]"       "Query objects within distance of another object")
		.def("near",                     &ObjectQuery::NearPoint,      return_value_policy<reference_existing_object>(),     "[near(self, point: Vec3) -> ObjectQuery]"    "Query objects within distance of a point")
		.def("targetable",               &ObjectQuery::Targetable,     return_value_policy<reference_existing_object>(),     "[targetable(self) -> ObjectQuery]"           "Query targetable. Not equivalent to UnitObj.targetable. This checks if obj is alive, targetable and not invulnerable")
		.def("untargetable",             &ObjectQuery::Untargetable,   return_value_policy<reference_existing_object>(),     "[untargetable(self) -> ObjectQuery]"         "Query untargetable")
		.def("visible",                  &ObjectQuery::Visible,        return_value_policy<reference_existing_object>(),     "[visible(self) -> ObjectQuery]"              "Query objects in vision")
		.def("invisible",                &ObjectQuery::Invisible,      return_value_policy<reference_existing_object>(),     "[invisible(self) -> ObjectQuery]"            "Query objects out of vision")
		.def("alive",                    &ObjectQuery::Alive,          return_value_policy<reference_existing_object>(),     "[alive(self) -> ObjectQuery]"                "Query alive objects")
		.def("dead",                     &ObjectQuery::Dead,           return_value_policy<reference_existing_object>(),     "[dead(self) -> ObjectQuery]"                 "Query dead objects")
		.def("clone",                    &ObjectQuery::IsClone,        return_value_policy<reference_existing_object>(),     "[clone(self) -> ObjectQuery]"                "Query clone objects")
		.def("not_clone",                &ObjectQuery::IsNotClone,     return_value_policy<reference_existing_object>(),     "[not_clone(self) -> ObjectQuery]"            "Query non clone objects")
		.def("on_screen",                &ObjectQuery::OnScreen,       return_value_policy<reference_existing_object>(),     "[on_screen(self) -> ObjectQuery]"            "Query objects on screen")
		.def("casting",                  &ObjectQuery::IsCasting,      return_value_policy<reference_existing_object>(),     "[casting(self) -> ObjectQuery]"              "Query units casting a spell")
		;


	class_<PyExecutionContext>("Context", "Contains everything necessarry to create scripts. From utility functions to game data")
		.def("info",                     &PyExecutionContext::LogInfo,                                                                  "[info(self, msg: str)]"    "Logs an info message to the console & file log")
		.def("warn",                     &PyExecutionContext::LogWarning,                                                               "[warn(self, msg: str)]"    "Logs a warning message to the console & file log")
		.def("error",                    &PyExecutionContext::LogError,                                                                 "[error(self, msg: str)]"   "Logs a error message to the console & file log. The file log will be flushed. Use this in absolute worse cases")
		.def_readonly("resources_loaded",&PyExecutionContext::everythingLoaded,                                                         "[bool] True if all valkyrie resources are loaded (images/jsons etc)")
		.def_readonly("ui",              &PyExecutionContext::GetImGuiInterface,                                                        "[UI] UI interface for drawing menus based on imgui")
		.def_readonly("cfg",             &PyExecutionContext::GetConfig,                                                                "[Config] The script config interface. Used to load/save settings")
		.def_readonly("time",            &PyExecutionContext::time,                                                                     "[float] Current game duration in seconds")
		.def_readonly("ping",            &PyExecutionContext::ping,                                                                     "[float] Current ping of the game")
		.def_readonly("cursor_pos",      &PyExecutionContext::GetMousePosition,                                                         "[Vec2] Gets the current position of the mouse")
																				                                                        
		.def_readonly("map",             &PyExecutionContext::gameMap,                                                                  "[Map] Currently played map")
		.def_readonly("keybinds",        &PyExecutionContext::keybinds,                                                                 "[Keybind] Keybinds for casting spells/items etc")
		.def_readonly("hud",             &PyExecutionContext::gameHud,                                                                  "[GameHud] Gets the game HUD")
		.def_readonly("hovered",         &PyExecutionContext::hovered,                                                                  "[Obj] Gets the game object under the mouse")
		.def_readonly("focused",         &PyExecutionContext::focused,                                                                  "[Obj] Gets the game object focused (the object that was last clicked). None if last click was not on a object")
		.def_readonly("player",          &PyExecutionContext::player,                                                                   "[ChampionObj] The champion used by the local player. In replays this will be a random champion")
		.def_readonly("champs",          &PyExecutionContext::GetChampions,                                                             "[ObjectQuery] Returns champion query builder")
		.def_readonly("turrets",         &PyExecutionContext::GetTurrets,                                                               "[ObjectQuery] Returns turrets query builder")
		.def_readonly("missiles",        &PyExecutionContext::GetMissiles,                                                              "[ObjectQuery] Returns missiles query builder")
		.def_readonly("minions",         &PyExecutionContext::GetMinions,                                                               "[ObjectQuery] Returns minions query builder")
		.def_readonly("jungle",          &PyExecutionContext::GetJungle,                                                                "[ObjectQuery] Returns jungle monster query builder")
		.def_readonly("others",          &PyExecutionContext::GetOthers,                                                                "[ObjectQuery] Returns other uncategorized objects query builder")
		
		.def("obj_by_net_id",            &PyExecutionContext::GetObjectWithNetworkId,                                                   "[obj_by_net_id(self, net_id: int) -> Obj] Returns the objects with the specified network id or None")
		.def("raycast",                  &PyExecutionContext::Raycast,                                                                  "[raycast(self, begin: Vec3, direction: Vec3, length: float, width: float, layers: RayLayer) -> RaycastResult] Launches a ray that stops on the first object specified by RayLayer")
		.def("raycast_multiple",         &PyExecutionContext::RaycastMultipleResults,                                                   "[raycast(self, begin: Vec3, direction: Vec3, length: float, width: float, layers: RayLayer) -> RaycastResult] Same as Context.Raycast but returns a list with all collision instead of the first collision.")
		
		.def("is_wall_at",               &PyExecutionContext::IsWallAt,                                                                 "[is_wall_at(self, position: Vec3) -> bool]"                                            "Checks if there is a wall at the specified position")
		.def("collisions_for",           &PyExecutionContext::GetCollisionsForUnit,                                                     "[collisions_for(unit: UnitObj)-> list[FutureCollision]]"                               "Gets a list of future collisions for a unit")
		.def("collisions_for",           &PyExecutionContext::GetCollisionsForCast,                                                     "[collisions_for(spell: SpellCast)-> list[FutureCollision]]"                            "Gets a list of future collisions for a spell cast")
		.def("collisions_for_unit",      &PyExecutionContext::GetCollisionsForUnit,                                                     "[collisions_for_unit(unit: UnitObj)-> list[FutureCollision]]"                          "Gets a list of future collisions for a unit")
		.def("collisions_for_spell",     &PyExecutionContext::GetCollisionsForCast,                                                     "[collisions_for_spell(spell: SpellCast)-> list[FutureCollision]]"                      "Gets a list of future collisions for a spell cast")
		
		.def("attack",                   &PyExecutionContext::AttackUnit,                                                               "[attack(self, target: UnitObj)]"                                                       "Makes the player attack the given unit")
		.def("move",                     &PyExecutionContext::MoveToLocation,                                                           "[move(self, location: Vec3)]"                                                          "Moves the player to the given location")
		.def("move",                     &PyExecutionContext::MoveToMouse,                                                              "[move(self)]"                                                                          "Moves the player to where the mouse cursor is")
		.def("move_to_location",         &PyExecutionContext::MoveToLocation,                                                           "[move_to_location(self, location: Vec3)]"                                              "Moves the player to where the mouse cursor is")
		.def("move_to_mouse",            &PyExecutionContext::MoveToMouse,                                                              "[move_to_mouse(self)]"                                                                 "Moves the player to where the mouse cursor is")
		
		.def("move_mouse",               &PyExecutionContext::MoveMouse,                                                                "[move_mouse(self, location: Vec3)]"                                                    "Moves the mouse location to the specified game world coordinate")
		.def("is_held",                  &PyExecutionContext::IsKeyDown,                                                                "[is_held(self, key: Key) -> bool]"                                                     "Checks if key is held down")
		.def("was_pressed",              &PyExecutionContext::WasKeyPressed,                                                            "[was_pressed(self, key: Key) -> bool]"                                                 "Checks if key was pressed")
		.def("set_key_active",           &PyExecutionContext::SetKeyActive,                                                             "[set_key_active(self, key: Key, active: bool)]"                                        "Programatically disable/enable game keys. This means nothing will happen in game when the key gets pressed but valkyrie will still recognize that key. Use ctx.keybinds to get keys")
																				                                                        
		.def("start_channel",            &PyExecutionContext::StartChannel,                                                             "[start_channel(self, spell: SpellObj) -> bool]"                                        "Starts a channeled spell")
		.def("end_channel",              &PyExecutionContext::EndChannel,                                                               "[end_channel(self, spell: SpellObj, location: Vec3) -> bool]"                          "Ends and casts the channeled spell at the target location")
		.def("cast_spell",               &PyExecutionContext::CastSpell,                                                                "[cast_spell(self, spell: SpellObj, location: Vec3) -> bool]"                           "Casts a spell on a location. If second argument is None, it will cast at the current mouse position. This function will check if spell is castable automatically. It doesnt check for item charge availability.")
		.def("cast_spell_on_unit",       &PyExecutionContext::CastSpellOnUnit,                                                          "[cast_spell_on_unit(self, spell: SpellObj, target: UnitObj) -> bool]"                  "Casts a spell on a unit using prediction. If spell cannot be cast for some reason (no mana, unable to hit target etc) it will return False")
		.def("predict_cast_point",       &PyExecutionContext::PredictCastPoint,                                                         "[predict_cast_point(self, caster: UnitObj, target: UnitObj, spell: SpellObj) -> Vec3]" "Predicts a cast point such that the spell will hit the target. Returns None if doesnt find such a point")
		.def("get_spell_static",         &PyExecutionContext::GetSpellInfo,                                                             "[get_spell_static(self, spell_name: str) -> SpellStatic]"                              "Gets static spell info. Argument must be lower case")
																				                                                        
		.def("is_under_tower",           &PyExecutionContext::IsUnderTower,                                                             "[is_under_tower(self, obj: Obj) -> bool]"                                              "True if the game object is under tower")
		.def("is_at_spawn",              &PyExecutionContext::IsInFountain,                                                             "[is_at_spawn(self, obj: Obj) -> bool]"                                                 "Checks if the object is in the fountain of his team")
		.def("is_on_screen",             &PyExecutionContext::IsScreenPointOnScreen, PyExecutionContext::IsScreenPointOnScreenOverloads("[is_on_screen(self, point: Vec2) -> bool]"                                             "True if point is on screen"))
		.def("is_on_screen",             &PyExecutionContext::IsWorldPointOnScreen,  PyExecutionContext::IsWorldPointOnScreenOverloads( "[is_on_screen(self, point: Vec3) -> bool]"                                             "True if point is on screen"))
		.def("is_screen_point_on_screen",&PyExecutionContext::IsScreenPointOnScreen, PyExecutionContext::IsScreenPointOnScreenOverloads("[is_scren_point_on_screen(self, point: Vec2) -> bool]"                                 "True if point is on screen"))
		.def("is_world_point_on_screen", &PyExecutionContext::IsWorldPointOnScreen,  PyExecutionContext::IsWorldPointOnScreenOverloads( "[is_world_point_on_screen(self, point: Vec3) -> bool]"                                 "True if point is on screen"))
		.def("w2s",                      &PyExecutionContext::World2Screen,                                                             "[w2s(self, position: Vec3) -> Vec2]"                                                   "Converts a world space point to screen space")
		.def("w2m",                      &PyExecutionContext::World2Minimap,                                                            "[w2m(self, position: Vec3) -> Vec2]"                                                   "Converts a world space point to minimap space")
		.def("d2m",                      &PyExecutionContext::DistanceOnMinimap,                                                        "[d2m(self, distance: float) -> float]"                                                 "Converts a distance value from world space to minimap space")
																				                                                        
		.def("ping_normal",              &PyExecutionContext::PingNormal,                                                               "[ping_normal(self, location: Vec3)]"                                                   "Issues a `normal` ping at the target location. For this ping type riot moves the cursor position to the ping location after ping has been issued")
		.def("ping_warn",                &PyExecutionContext::PingWarn,                                                                 "[ping_warn(self, location: Vec3)]"                                                     "Issues a `back` ping at the target location. For this ping type riot moves the cursor position to the ping location after ping has been issued")
		.def("ping_danger",              &PyExecutionContext::PingDanger,                                                               "[ping_danger(self, location: Vec3)]"                                                   "Issues a `danger` ping at the target location")
		.def("ping_mia",                 &PyExecutionContext::PingMia,                                                                  "[ping_mia(self, location: Vec3)]"                                                      "Issues a `enemy missing` ping at the target location")
		.def("ping_omw",                 &PyExecutionContext::PingOmw,                                                                  "[ping_omw(self, location: Vec3)]"                                                      "Issues a `on my way` ping at the target location")
		.def("ping_vision",              &PyExecutionContext::PingVision,                                                               "[ping_vision(self, location: Vec3)]"                                                   "Issues a `warded` ping at the target location")
		.def("ping_assist",              &PyExecutionContext::PingAssist,                                                               "[ping_assist(self, location: Vec3)]"                                                   "Issues a `help` ping at the target location")

		.def("hp_dmg_indicator",         &PyExecutionContext::DrawHpBarDamageIndicator,                                                 "[hp_dmg_indicator(self, champ: ChampionObj, dmg: float, color: Col)] Draws an damage indicator with a specified color for an amount of damage on a champion hp bar.")
		.def("line",                     &PyExecutionContext::DrawLine,                                                                 "[line(self, start: Vec2, end: Vec2, thickness: float, color: Col)]")
		.def("line",                     &PyExecutionContext::DrawLineWorld,                                                            "[line(self, start: Vec3, end: Vec3, thickness: float, color: Col))]")
		.def("circle",                   &PyExecutionContext::DrawCircle,                                                               "[circle(self, center: Vec2, radius: float, num_pts: int, thickness: float, color: Col)]")
		.def("circle_fill",              &PyExecutionContext::DrawCircleFilled,                                                         "[circle_fill(self, center: Vec2, radius: float, num_pts: int, color: Col)]")
		.def("circle",                   &PyExecutionContext::DrawCircleWorld,                                                          "[circle(self, center: Vec3, radius: float, num_pts: int, thickness: float, color: Col)]")
		.def("circle_fill",              &PyExecutionContext::DrawCircleWorldFilled,                                                    "[circle_fill(self, center: Vec3, radius: float, num_pts: int, color: Col)]")
		.def("text",                     &PyExecutionContext::DrawTxt,                                                                  "[text(self, position: Vec2, text: str, color: Col)]")		
		.def("rect",                     &PyExecutionContext::DrawRect,                           PyExecutionContext::DrawRectOverloads("[rect(self, start: Vec2, size: Vec2, color: Col, rounding: float, thickness: float)]"))
		.def("rect_fill",                &PyExecutionContext::DrawRectFilled,               PyExecutionContext::DrawRectFilledOverloads("[rect_fill(self, start: Vec2, size: Vec2, color: Col, rounding: float)]"))
		.def("rect",                     &PyExecutionContext::DrawRectWorld,                                                            "[rect(self, p1: Vec3, p2: Vec3, p3: Vec3, p4: Vec3, thickness: float, color: Col)]")
		.def("triangle",                 &PyExecutionContext::DrawTriangleWorld,                                                        "[triangle(self, p1: Vec3, p2: Vec3, p3: Vec3, thickness: float, color: Col)]")
		.def("triangle_fill",            &PyExecutionContext::DrawTriangleWorldFilled,                                                  "[triangle_fill(self, p1: Vec3, p2: Vec3, p3: Vec3, color: Col)]")
		
		.def("image",                    &PyExecutionContext::DrawImage,                                                                "[image(self, id: str, position: Vec2, size: Vec2, color: Col)]")
		.def("image",                    &PyExecutionContext::DrawImageUVs,                                                             "[image(self, id: str, position: Vec2, uv1: Vec2, uv2: Vec2, size: Vec2, color: Col)]")
		.def("image",                    &PyExecutionContext::DrawImageRounded,                                                         "[image(self, id: str, position: Vec2, size: Vec2, color: Col, rounding: float)]")
		.def("image",                    &PyExecutionContext::DrawImageWorld,                                                           "[image(self, id: str, position: Vec3, size: Vec2, color: Col)]")
		.def("image",                    &PyExecutionContext::DrawImageWorldPoints,                                                     "[image(self, id: str, p1: Vec3, p2: Vec3, p3: Vec3, p4: Vec4, color: Col)]")
		
		/// Overloads from above but with a different alias so ppl see them in IDEs
		.def("circle_world",             &PyExecutionContext::DrawCircleWorld,                                                          "[circle_world(self, center: Vec3, radius: float, num_pts: int, thickness: float, color: Col)]")
		.def("circle_word_fill",         &PyExecutionContext::DrawCircleWorldFilled,                                                    "[circle_world_fill(self, center: Vec3, radius: float, num_pts: int, color: Col)]")
		.def("rect_world",               &PyExecutionContext::DrawRectWorld,                                                            "[rect_world(self, p1: Vec3, p2: Vec3, p3: Vec3, p4: Vec3, thickness: float, color: Col)]")
		.def("image_uvs"  ,              &PyExecutionContext::DrawImageUVs,                                                             "[image_uvs(self, id: str, position: Vec2, uv1: Vec2, uv2: Vec2, size: Vec2, color: Col)]")
		.def("image_rounded",            &PyExecutionContext::DrawImageRounded,                                                         "[image_rounded(self, id: str, position: Vec2, size: Vec2, color: Col, rounding: float)]")
		.def("image_world",              &PyExecutionContext::DrawImageWorld,                                                           "[image_world(self, id: str, position: Vec3, size: Vec2, color: Col)]")
		.def("image_world_fixed",        &PyExecutionContext::DrawImageWorldPoints,                                                     "[image_world_fixed(self, id: str, p1: Vec3, p2: Vec3, p3: Vec3, p4: Vec4, color: Col)]")

		.def("pill",                     &PyExecutionContext::Pill,                                                                     "[pill(self, text: str, color_text: Col, color_background: Col)] Draws a pill with a text under the player. Pill positions are automatically managed each frame so that they dont overlap.")
		;
}